name: DEBUG

on:
  push:
    branches:
      - master

jobs:
  debug:
    name: DEBUG
    runs-on: ubuntu-latest
    steps:
      - name: this repo
        run: |
          curl -i \
            -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/mshick/add-pr-comment-proxy/issues

      - name: another repo
        run: |
          curl -i \
            -X GET \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/mshick/add-pr-comment/issues
